version: "3"

services:
  postit_configserver:
    container_name: postit-configserver
    build:
      context: ConfigServer
      dockerfile: Dockerfile-local
    ports:
      - 8888:8888

  postit_eurekaserver:
    container_name: postit-eurekaserver
    build:
      context: EurekaServer
      dockerfile: Dockerfile-local
    ports:
      - 8761:8761
    depends_on:
      - postit_configserver

  postit_zuulserver:
    container_name: postit-zuulserver
    build:
      context: ZuulServer
      dockerfile: Dockerfile-local
    ports:
      - 5555:5555
    depends_on:
      - postit_configserver

  postit_authserver:
    container_name: postit-authserver
    build:
      context: AuthServer
      dockerfile: Dockerfile-local
    ports:
      - 8443:8443
    depends_on:
      - postit_configserver

  postit_reportserver:
    container_name: postit-reportserver
    build:
      context: ReportServer
      dockerfile: Dockerfile-local
    ports:
      - 8000:8000
    depends_on:
      - postit_configserver
