#포트변경
server:
  port: 8000
#mongodb 설정
spring:
  data:
    mongodb:
      authentication-database: postit
      username: ssafy103pi
      password: postit123
      host: j4c103.p.ssafy.io
      port: 27017
      database: postit
  cache:
    type: redis
  redis:
    host: j4c103.p.ssafy.io
    port: 8999
    password: ssafy103postit

# openapi 3.0 설정
springdoc:
  version: "@project.version@"
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  # controller path 등록
  paths-to-match:
    - /api/v1/**
    - /main/**
    - /blog/**
    - /youtube/**
    - /report/**
    - /job/**

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true # 유레카 서비스에 자신을 등록
    fetchRegistry: true # 레즈스트리의 로컬 복사본 가져오게 허용
    serviceUrl: # 유레카 클러스터 구축
      defaultZone: http://postit-eurekaserver:8761/eureka/
